version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    volumes:
      - ./shared:/app/shared
    environment:
      - PYTHONPATH=/app/shared

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    volumes:
      - ./shared:/app/shared
    environment:
      - PYTHONPATH=/app/shared